# Generated by Django 6.0.3 on 2026-05-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_new_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deviceregistration',
            new_name='alerts_devi_firebas_737182_idx',
            old_name='alerts_devi_firebas_idx',
        ),
    ]
