"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY SETTINGS

SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-dev-only-change-this-before-production",
)

DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="127.0.0.1,localhost",
    cast=lambda value: [host.strip() for host in value.split(",")],
)

# Cookies are only ever sent to clients over HTTPS (TLS terminates at
# Cloudflare), so marking them secure costs nothing and stops them leaking over
# a plaintext hop. Overridable so plain-HTTP local development still works.
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=not DEBUG, cast=bool)

# Django 4+ validates the Origin header against this list for unsafe methods.
#
# Leaving it empty broke every session-authenticated POST in production,
# including the admin login form. TLS terminates at Cloudflare and nginx
# forwards X-Forwarded-Proto: http (see the note below), so Django believes it
# is serving plain HTTP and expects "http://<host>" while the browser sends
# "https://<host>" -- Origin mismatch, 403 "CSRF verification failed".
#
# So when the setting is unset we derive it from ALLOWED_HOSTS: every real host
# is trusted over https. Set CSRF_TRUSTED_ORIGINS explicitly to override.
def _origins_from_allowed_hosts(hosts):
    origins = []
    for host in hosts:
        if host == "*":
            # "https://*" is not a valid trusted origin; nothing to derive.
            continue
        # Django spells a wildcard subdomain host as ".example.com".
        origins.append(f"https://*{host}" if host.startswith(".") else f"https://{host}")
    return origins


CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="",
    cast=lambda value: [o.strip() for o in value.split(",") if o.strip()],
) or _origins_from_allowed_hosts(ALLOWED_HOSTS)

# DELIBERATELY OFF BY DEFAULT.
#
# Enabling either of these on the current infrastructure takes the site down.
# nginx listens on port 80 only (Cloudflare terminates TLS) and
# /etc/nginx/snippets/proxy.conf sets `X-Forwarded-Proto $scheme`, which
# overwrites Cloudflare's "https" with "http". Django would therefore never
# see a secure request: SECURE_SSL_REDIRECT would redirect forever, and
# SECURE_HSTS_SECONDS would be served from a origin that believes it is
# plaintext.
#
# To turn these on, first change that snippet to forward the real value:
#     proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
# then set SECURE_PROXY_SSL_HEADER below and flip these in .env.
# Note the snippet is shared by every site on the host, so changing it affects
# more than this project. HSTS in particular is hard to undo once a browser has
# cached it -- start with a small SECURE_HSTS_SECONDS and raise it.
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=False, cast=bool)
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False, cast=bool
)
SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", default=False, cast=bool)

if config("USE_X_FORWARDED_PROTO", default=False, cast=bool):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# APPLICATION DEFINITION

INSTALLED_APPS = [
    'django.contrib.gis',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'alerts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Serves files from STATIC_ROOT under gunicorn, which (unlike runserver)
    # does not serve static files itself. Must sit directly after
    # SecurityMiddleware and before everything else.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# DATABASE CONFIGURATION

if config("POSTGRES_HOST", default=None):
    DATABASES = {
        "default": {
            "ENGINE": "django.contrib.gis.db.backends.postgis",
            "NAME": config("POSTGRES_DB", default="rescue_alert"),
            "USER": config("POSTGRES_USER", default="rescue_user"),
            "PASSWORD": config("POSTGRES_PASSWORD", default="change_me_now"),
            "HOST": config("POSTGRES_HOST", default="db"),
            "PORT": config("POSTGRES_PORT", default="5432"),
        }
    }
else:
    # Fallback to SQLite for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# PASSWORD VALIDATION

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# INTERNATIONALIZATION

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# STATIC FILES

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# DEFAULT PRIMARY KEY FIELD TYPE

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# REST FRAMEWORK

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'alerts.authentication.FirebaseAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Rescue Alert System API',
    'DESCRIPTION': (
        'Production API for the Rescue Alert System.\n\n'
        '**How to authenticate:**\n'
        '1. Click the **Get Token** button at the top of the page\n'
        '2. Sign in with Google and copy the token\n'
        '3. Click **Authorize** below, paste the token, click **Authorize**\n\n'
        'Token expires after 1 hour — repeat to refresh.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'TAGS': [
        {
            'name': 'TEST',
            'description': (
                '🔴 **Start here.** Use `GET /api/auth/whoami/` to confirm your token is valid '
                'before calling any other endpoint. A 200 response means you are authenticated.'
            ),
        },
        {'name': 'alerts', 'description': 'Create and retrieve fire/rescue alerts.'},
        {'name': 'user', 'description': 'User profiles and location updates.'},
        {'name': 'group', 'description': 'Rescue groups and membership.'},
        {'name': 'message', 'description': 'In-app messages between users.'},
        {'name': 'notification', 'description': 'Push notification records.'},
    ],
    'SWAGGER_UI_SETTINGS': {
        'tagsSorter': None,
        'persistAuthorization': True,
        'deepLinking': True,
    },
}


# CORS

CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:5173,http://localhost:4173",
    cast=lambda v: [o.strip() for o in v.split(",")],
)